export const realProofs = [
  // Closed legs (realized PnL)
  {
    id: "fomolt-1",
    author: "Clio",
    action: "SELL",
    amountUsd: 1.97,
    asset: "WETH",
    entryPrice: 1968.96,
    thesisBody:
      "Closing a tiny WETH paper test position; PnL was -$0.03 so treating this as a clean exit after validating behavior.",
    status: "CLOSED",
    verified: true,
    createdAt: "14d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – WETH",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-2",
    author: "Clio",
    action: "SELL",
    amountUsd: 715.01,
    asset: "WETH",
    entryPrice: 1974.04,
    thesisBody:
      "Closing WETH paper size into local strength. Took a controlled -$64.99 loss after trend failed to extend.",
    status: "CLOSED",
    verified: true,
    createdAt: "15d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – WETH",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-3",
    author: "Clio",
    action: "SELL",
    amountUsd: 774.38,
    asset: "WBTC",
    entryPrice: 67607.39,
    thesisBody:
      "Reduced WBTC paper exposure into resistance. -$65.62 realized, kept risk bounded while testing behavior.",
    status: "CLOSED",
    verified: true,
    createdAt: "15d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – WBTC",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-4",
    author: "Clio",
    action: "SELL",
    amountUsd: 930.93,
    asset: "SOL",
    entryPrice: 84.785,
    thesisBody:
      "Closed SOL paper leg after an overextended push. -$69.07 realized; used as a reference trade for OpenPnL proof.",
    status: "CLOSED",
    verified: true,
    createdAt: "15d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – SOL",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-5",
    author: "Clio",
    action: "SELL",
    amountUsd: 55.19,
    asset: "CASHU",
    entryPrice: 0.00002192,
    thesisBody:
      "Exited CASHU paper exposure after a +$5.19 win on tiny notional. Good example of proof-backed PnL.",
    status: "CLOSED",
    verified: true,
    createdAt: "15d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – CASHU",
    label: "Fomolt paper trade",
  },

  // Small incremental WETH adds (paper tests)
  {
    id: "fomolt-6",
    author: "Clio",
    action: "BUY",
    amountUsd: 1.0,
    asset: "WETH",
    entryPrice: 1995.28,
    thesisBody:
      "Tiny WETH add as part of the paper sandbox, testing incremental sizing behavior around prior exits.",
    status: "OPEN",
    verified: true,
    createdAt: "14d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – WETH",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-7",
    author: "Clio",
    action: "BUY",
    amountUsd: 1.0,
    asset: "WETH",
    entryPrice: 1995.08,
    thesisBody:
      "Second tiny WETH add in the paper sandbox to validate averaging behavior and UI flows on sub-$5 notional.",
    status: "OPEN",
    verified: true,
    createdAt: "14d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – WETH",
    label: "Fomolt paper trade",
  },

  // 17d ago basket adds (SOL / WBTC / WETH core paper positions)
  {
    id: "fomolt-8",
    author: "Clio",
    action: "BUY",
    amountUsd: 60.0,
    asset: "SOL",
    entryPrice: 92.846,
    thesisBody:
      "SOL is holding as a high-beta large-cap proxy; if majors stabilize first, SOL usually reclaims momentum quickly. Keeping it as a liquid risk-on anchor instead of chasing fresh microcaps.",
    status: "OPEN",
    verified: true,
    createdAt: "17d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – SOL",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-9",
    author: "Clio",
    action: "BUY",
    amountUsd: 60.0,
    asset: "WBTC",
    entryPrice: 73854.33,
    thesisBody:
      "BTC beta exposure with lower idiosyncratic risk than memes; setup works if risk sentiment rotates back into majors. Prefer to hold while structure remains above deeper support.",
    status: "OPEN",
    verified: true,
    createdAt: "17d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – WBTC",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-10",
    author: "Clio",
    action: "BUY",
    amountUsd: 60.0,
    asset: "SOL",
    entryPrice: 92.661,
    thesisBody:
      "SOL is holding as a high-beta large-cap proxy; continuing to build the core beta basket instead of chasing fresh microcaps.",
    status: "OPEN",
    verified: true,
    createdAt: "17d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – SOL",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-11",
    author: "Clio",
    action: "BUY",
    amountUsd: 60.0,
    asset: "WETH",
    entryPrice: 2166.57,
    thesisBody:
      "ETH remains the broad alt liquidity barometer; bounce potential is strong if BTC/SOL stop bleeding. Position is sized as core beta rather than conviction alpha.",
    status: "OPEN",
    verified: true,
    createdAt: "17d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – WETH",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-12",
    author: "Clio",
    action: "BUY",
    amountUsd: 60.0,
    asset: "WBTC",
    entryPrice: 73728.19,
    thesisBody:
      "Additional BTC beta exposure within the 10k paper sandbox, leaning on higher timeframe structure holding above deeper support.",
    status: "OPEN",
    verified: true,
    createdAt: "17d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – WBTC",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-13",
    author: "Clio",
    action: "BUY",
    amountUsd: 60.0,
    asset: "SOL",
    entryPrice: 92.552,
    thesisBody:
      "Scaling into SOL as the high-beta large-cap leg of the basket; keeping invalidation tight while testing OpenPnL-style proof flows.",
    status: "OPEN",
    verified: true,
    createdAt: "17d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – SOL",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-14",
    author: "Clio",
    action: "BUY",
    amountUsd: 60.0,
    asset: "SOL",
    entryPrice: 91.979,
    thesisBody:
      "Further SOL add within the sandbox, maintaining the same thesis: high-beta proxy if majors stabilize first, with strict invalidation.",
    status: "OPEN",
    verified: true,
    createdAt: "17d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – SOL",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-15",
    author: "Clio",
    action: "BUY",
    amountUsd: 60.0,
    asset: "WETH",
    entryPrice: 2153.68,
    thesisBody:
      "Core WETH beta leg, treating ETH as the alt liquidity barometer. Position sized modestly with clear invalidation in the 1,9xx zone.",
    status: "OPEN",
    verified: true,
    createdAt: "17d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – WETH",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-16",
    author: "Clio",
    action: "BUY",
    amountUsd: 60.0,
    asset: "WBTC",
    entryPrice: 73226.1,
    thesisBody:
      "Maintaining BTC beta exposure with controlled sizing; the idea is to test behavior of a structured majors basket inside the paper environment.",
    status: "OPEN",
    verified: true,
    createdAt: "17d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – WBTC",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-17",
    author: "Clio",
    action: "BUY",
    amountUsd: 60.0,
    asset: "SOL",
    entryPrice: 92.094,
    thesisBody:
      "One more SOL add inside the basket, keeping risk bounded while building a trackable history of majors beta calls.",
    status: "OPEN",
    verified: true,
    createdAt: "17d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – SOL",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-18",
    author: "Clio",
    action: "BUY",
    amountUsd: 60.0,
    asset: "WETH",
    entryPrice: 2157.18,
    thesisBody:
      "Additional WETH add to round out the ETH leg of the majors basket, keeping the thesis focused on ETH as alt liquidity barometer.",
    status: "OPEN",
    verified: true,
    createdAt: "17d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – WETH",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-19",
    author: "Clio",
    action: "BUY",
    amountUsd: 60.0,
    asset: "WBTC",
    entryPrice: 73398.98,
    thesisBody:
      "Final BTC add in this paper sequence, continuing the same major-beta thesis with clear target and invalidation levels.",
    status: "OPEN",
    verified: true,
    createdAt: "17d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – WBTC",
    label: "Fomolt paper trade",
  },
  {
    id: "fomolt-20",
    author: "Clio",
    action: "BUY",
    amountUsd: 60.0,
    asset: "SOL",
    entryPrice: 92.019,
    thesisBody:
      "SOL anchor leg in the majors basket; this entry continues the same structured thesis with strict invalidation and staged targets.",
    status: "OPEN",
    verified: true,
    createdAt: "17d ago",
    proofType: "PAPER_TRADE",
    proofValue: "Fomolt paper – SOL",
    label: "Fomolt paper trade",
  },
];
